### ISSUE TITLE
After loading post, how compatible with other plugins, such as sliders or video plugins,Thank you

### ISSUE THREAD

**Issue by zhw2590582** [synapticism/wp-ajax-page-loader#1]
After loading post, how compatible with other plugins, such as sliders or video plugins,Thank you

**Comment by synapticism** [comment]
It hasn't been widely tested but there shouldn't be any problems with most scripts. This script is properly namespaced and encapsulated so it shouldn't collide with anything else.

One area you might have some trouble is with conditionally loaded scripts. So, for instance, if you have a script that only loads when certain kinds of content are being displayed and you start on a page that doesn't already load the script you might be out of luck. New content will be loaded but the extra script won't be.
