### ISSUE TITLE
Request: append all loaded posts into the same container

### ISSUE THREAD

**Issue by henrilindeberg** [synapticism/wp-ajax-page-loader#2]
To use the loader with masorny layout I need all the posts to be loaded into the original container without the "content-page-..." wrapper.

Would it be possible to attcheave somehow?

**Comment by synapticism** [comment]
I'm not sure this is possible without abandoning paging functionality. The History API relies on those containers to update the URL. If you're only looking to load content into the main container then you may have better luck using one of the original infinite scroll plugins.

**Comment by synapticism** [comment]
Updated the readme with some alternatives to consider.
